### ISSUE TITLE
Master Bug List

### ISSUE THREAD

**Issue by rajbirjohar** [c2c-project/prytaneum-client#128] opened 2021-09-18 15:30 UTC
## Purpose
This particular issue is to list out all the bugs encountered on the production deployment. All you have to do is comment on this thread and record any potential issues or glaring bugs that are seen.

### UI/UX
- When logging in on Safari, the side navigation does not show. It works on Chrome and Firefox.
- The footer is too tall. Either reduce the size or figure out a way to make the live page full screen.

### Functionality
- ~~"An unexpected error occurred" page shows up on Firefox and Safari. It works on Chrome. This is the Vercel default error page so I think it may be a 500 error.~~ This bug seems to have been fixed.

**Comment by claynaut** [comment] 2021-09-18 18:56
### UI/UX
- **Login Modal**
  - When you click "Forgot Password?", the modal doesn't close on page redirect
- ~~**Creating Organizations**~~
  - ~~When creating an organization and you try to submit a blank form, the name field isn't highlighted red and you are not notified to fill out the field (e.g. "Please enter an organization name.")~~
- ~~**Organization - Adding Members**~~
  - ~~When adding a member to an organization, any input can be submitted (e.g. no input, "aaa")~~
    - ~~As a result, member is added with the name "null null"~~
    - ~~When adding a member with a valid email format and no member exists with that email, a member is still added with the name "null null"~~
      - ~~You are not notified that no member exists with that email~~
- ~~**Organization - Creating Events**~~
  - ~~When creating events, even though description appears to be required (has a *), you are not notified to fill out a description (e.g. "Please enter a description") like how they are notified to fill out a topic and a title~~
    - ~~A blank description can be submitted (unsure if the description is meant to be optional)~~
- ~~**Organization - Event Settings**~~
  - ~~The subheading "User Settings" is shown right underneath "Event Settings"~~
    - ~~A settings component may have been reused and the title "User Settings" just hasn't been changed~~
  - ~~**Details**~~
    - ~~There are no spaces between the words for the start date/time and end date/time~~
      - ~~The label is shown as "STARTDATETIME" and "ENDDATETIME" (unsure if the label is meant to be "START DATE & TIME" and "END DATE & TIME")~~
  - ~~**Videos**~~
    - ~~When you add videos, a blank Video Form can be submitted~~
      - ~~As a result, this creates an item in the list with blank Language/Video URL fields~~
  - ~~**Speakers**~~
    - ~~When attempting to submit a blank Speaker Form, only the "Picture URL" field is highlighted red as required~~
      - ~~When submitting with a filled out "Picture URL," the form doesn't submit but the other fields are not highlighted red to indicate that they're required as well~~
    - ~~When adding a speaker, an invalid email can be submitted (e.g. "aaa")~~
  - ~~**Moderators**~~
    - ~~When attempting to submit a blank Moderator Form, the form doesn't submit but you are not notified to fill out the required field (e.g. "Please enter an email.")~~
    - ~~When adding a moderator, nonexistent users can be added (i.e. valid emails are inputted but no user exists with that email)~~ (not a bug)
      - ~~As a result, a user with the name "null null" is added to the moderator list~~
    - ~~When attempting to update an existing moderator, you can't submit the Moderator Form~~ (not a bug)
      - ~~As a result, you can't update the existing moderator~~
- ~~**User Settings**~~
  - ~~**Change Email**~~
    - ~~When leaving all the required fields blank and submitting the form, you are redirected to basically the same page (the same page is shown but the url is different and contains the form details)~~
      - ~~You are not notified to fill out any of the required fields and none of the fields are highlighted red to signify being required~~
  - ~~**Change Password**~~
      - ~~When leaving all the required fields blank and submitting the form, you are redirected to basically the same page (the same page is shown but the url is different and contains the form details)~~
        - ~~You are not notified to fill out any of the required fields and none of the fields are highlighted red to signify being required~~
        - ~~Not all the fields have to be filled out to be able to submit the form (upon submitting, you are redirected as described above)~~
  - ~~**Delete Account**~~
      - ~~When leaving all the required fields blank and submitting the form, you are redirected to basically the same page (the same page is shown but the url is different and contains the form details)~~
        - ~~You are not notified to fill out any of the required fields and none of the fields are highlighted red to signify being required~~
        - ~~Not all the fields have to be filled out to be able to submit the form (upon submitting, you are redirected as described above)~~
  - ~~Form validation doesn't work as expected (helper text/red highlighting doesn't appear when submitting a blank form)~~
- **User Profile Dropdown Menu**
  - Using Google Chrome, sometimes you are unable to log out without refreshing the page, or closing the tab and creating a new tab to open the site from (reproducing this bug does not have a 100% chance)
- ~~**Footer**~~
  - ~~When clicking Login under Account, you are not redirected to the login page~~
  - ~~When clicking Sign Up under Account, you are not redirected to the register page~~
  - ~~When signed in, Login/Sign Up are still shown under Account (unsure if this is meant to stay despite you being logged in)~~

**Closed as completed** 2022-01-27 03:05 UTC
Labels: bug
